title : Anvar Karimson
description: "/dev/random"

#url: "http://localhost:4000"
url: "http://karimson.com"

exclude: [README.md, Rakefile]
paginate: 16
permalink: /posts/:title
pygments: true

analytics: UA-268439-9

author :
  name : Anvar Karimson
  github : anvar
  twitter : anvarkarimson
  linkedin : anvarkarimson
